# A. Titanic Dataset

In [2]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Q2) Create a contingency table showing the number of passengers according to their sex and survival status

In [4]:
table=pd.crosstab(df.sex,df.survived)
print(table)

survived    0    1
sex
female     81  233
male      468  109

Q3) Estimated the joint probability that a randomly selected passenger was female and survived.

In [5]:
female_and_survived=((df.sex == 'female') & (df.survived == 1)).sum() # total no of female survived

total =len(df) # total no of rows

p_female_and_survived=female_and_survived/total # defination of the probability

print("probaility of female and servived",p_female_and_survived)

probaility of female and servived 0.2615039281705948

Q4) Estimated the conditional probility that a passenger survived, given that the passenger was female

In [9]:
female = (df.sex == 'female').sum()
female_and_survived = ((df.sex == 'female') & (df.survived == 1)).sum()
p_survived_given_female = female_and_survived / female

print("Conditional probability:- P(survived | female)",p_survived_given_female)

Conditional probability:- P(survived | female) 0.7420382165605095

Q5) Estimate the conditional probability that a passenger survived, given that the passenger was male. Compare i twith the probability obtained in Q4

In [11]:
male=(df.sex=='male').sum()
male_and_survived=((df.sex=='male') & (df.survived==1)).sum()
p_survived_given_male=male_and_survived/male

print("conditional probablilty:- P(Survived | Male)",p_survived_given_male)
print("Conditional probability:- P(survived | female)",p_survived_given_female)

conditional probablilty:- P(Survived | Male) 0.18890814558058924
Conditional probability:- P(survived | female) 0.7420382165605095

Q6) Estimate the probability of survival conditional on passenger class

In [12]:
survival_by_class=df.groupby('class')['survived'].mean()
print(survival_by_class)

class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64

/tmp/ipykernel_979/2084018236.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_by_class=df.groupby('class')['survived'].mean()

# B. Penguin Dataset

Q1) Load the palmer Penguins dataset and display the first five observatios. Also find the number of observation and variables

In [20]:
import seaborn as sns
df=sns.load_dataset('penguins')
print(df.head(),"\n")
print("no of obervations",df.shape) # output(obervation, variable)

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
3  Adelie  Torgersen             NaN            NaN                NaN
4  Adelie  Torgersen            36.7           19.3              193.0

   body_mass_g     sex
0       3750.0    Male
1       3800.0  Female
2       3250.0  Female
3          NaN     NaN
4       3450.0  Female

no of obervations (344, 7)

Q2) Find the Frequency Distribution of species, island, and sex

In [25]:
df[['species','island','sex']].value_counts()

species    island     sex
Gentoo     Biscoe     Male      61
                      Female    58
Chinstrap  Dream      Female    34
                      Male      34
Adelie     Dream      Male      28
                      Female    27
           Torgersen  Female    24
                      Male      23
           Biscoe     Male      22
                      Female    22
Name: count, dtype: int64

Q3) Construct a contingency table showing the number of penguins belonging to each species on each island

In [26]:
contingency_table = pd.crosstab(df.species, df.island)
print(contingency_table)

island     Biscoe  Dream  Torgersen
species
Adelie         44     56         52
Chinstrap       0     68          0
Gentoo        124      0          0

Q4) Find the joint probability that a randomly selected penguin is an Adelie penguin AND is found on Dream island

In [31]:
penguin_adelie_and_dream_island = ((df.species == 'Adelie') & (df.island == 'Dream')).sum()
total=len(df)
joint_probability = penguin_adelie_and_dream_island / total
print(joint_probability)

0.16279069767441862

Q5) Find the joint probability that a randomly selected penguin is an Gentoo penguin AND is found on Biscoe island

In [32]:
penguin_gentoo_and_biscoe_island = ((df.species == 'Gentoo') & (df.island == 'Biscoe')).sum()
total=len(df)
joint_probability = penguin_gentoo_and_biscoe_island / total
print(joint_probability)

0.36046511627906974

Q6) Calculate the conditional probability that a penguin is an Adelie penguin given that it is found on Dream island

In [35]:
Dream = (df.island == 'Dream').sum()
Adelie_and_Dream = ((df.species == 'Adelie') & (df.island == 'Dream')).sum()
p_Adelie_given_Dream = Adelie_and_Dream / Dream

print("Conditional probability:- P(Adelie | Dream)",p_Adelie_given_Dream)

Conditional probability:- P(Adelie | Dream) 0.45161290322580644

Q7) Calculate the conditional probability that a penguin is an male given that it belong to the gentoo species

In [37]:
Gentoo = (df.species == 'Gentoo').sum()
Male_and_Gentoo = ((df.sex == 'Male') & (df.species == 'Gentoo')).sum()
p_Male_given_Gentoo  = Male_and_Gentoo / Gentoo

print("Conditional probability:- P(Male | Gentoo)",p_Male_given_Gentoo)

Conditional probability:- P(Adelie | Dream) 0.49193548387096775

Q8. Construct a contingency table for species and sex. Then calculate the probability that a randomly selected penguin is female and belongs to the Chinstrap species.

In [42]:
contingency_table = pd.crosstab(df.species, df.sex)
print(contingency_table)

df.sex == 'Female'
df.species == 'Chinstrap'
total=len(df)
probability_sex_species = ((df.sex == 'Female') & (df.species == 'Chinstrap')).sum() / total
print("Probability that a randomly selected penguin is female and belongs to the Chinstrap species:", probability_sex_species)

sex        Female  Male
species
Adelie         73    73
Chinstrap      34    34
Gentoo         58    61
Probability that a randomly selected penguin is female and belongs to the Chinstrap species: 0.09883720930232558

Q9. Calculate the probability of a penguin being male for each species. Use groupby().

In [50]:
probability_male_by_species = df.groupby('species')['sex'].apply(lambda x: (x == 'Male').mean())
print(probability_male_by_species)

species
Adelie       0.480263
Chinstrap    0.500000
Gentoo       0.491935
Name: sex, dtype: float64

Q10. Test whether species and island can be considered independent using :    P(A∩B)=P(A)P(B)Take:
A : Penguin is Gentoo
B : Penguin is found on Biscoe Island

In [57]:
Gentoo_count = (df.species == 'Gentoo').sum()
Biscoe_count = (df.island == 'Biscoe').sum()
Gentoo_and_Biscoe_count = ((df.species == 'Gentoo') & (df.island == 'Biscoe')).sum()
total = len(df)

p_Gentoo_and_Biscoe = Gentoo_and_Biscoe_count / total
p_Gentoo = Gentoo_count / total
p_Biscoe = Biscoe_count / total

P_A_times_P_B = p_Gentoo * p_Biscoe

print("P(Gentoo and Biscoe):", p_Gentoo_and_Biscoe)
print("P(Gentoo) * P(Biscoe):", P_A_times_P_B)
print("Are A and B independent :",p_Gentoo_and_Biscoe == P_A_times_P_B )

P(Gentoo and Biscoe): 0.36046511627906974
P(Gentoo) * P(Biscoe): 0.17604110329908057
Are A and B independent : False

In [58]:
p_Gentoo = (df.species == 'Gentoo').mean()
p_Biscoe = (df.island == 'Biscoe').mean()
p_Gentoo_and_Biscoe = ((df.species == 'Gentoo') & (df.island == 'Biscoe')).mean()

P_A_times_P_B = p_Gentoo * p_Biscoe

print("P(Gentoo and Biscoe):", p_Gentoo_and_Biscoe)
print("P(Gentoo) * P(Biscoe):", P_A_times_P_B)
print("Are A and B independent :",p_Gentoo_and_Biscoe == P_A_times_P_B )

P(Gentoo and Biscoe): 0.36046511627906974
P(Gentoo) * P(Biscoe): 0.17604110329908057
Are A and B independent : False